--- 
products_008: 
  permalink: classic-product-7
  updated_at: 2008-12-12 06:56:11
  title: Classic Product 7
  id: "204"
  description: 
  category_id: "60"
  created_at: 2008-12-12 06:56:11
products_030: 
  permalink: modern-product-6
  updated_at: 2008-12-12 06:56:11
  title: Modern Product 6
  id: "226"
  description: 
  category_id: "63"
  created_at: 2008-12-12 06:56:11
products_029: 
  permalink: modern-product-5
  updated_at: 2008-12-12 06:56:11
  title: Modern Product 5
  id: "225"
  description: 
  category_id: "63"
  created_at: 2008-12-12 06:56:11
products_051: 
  permalink: baby-announcements-thank-yous-product-2
  updated_at: 2008-12-12 06:56:11
  title: Baby Announcements & Thank Yous Product 2
  id: "247"
  description: 
  category_id: "72"
  created_at: 2008-12-12 06:56:11
products_010: 
  permalink: classic-product-9
  updated_at: 2008-12-12 06:56:11
  title: Classic Product 9
  id: "206"
  description: 
  category_id: "60"
  created_at: 2008-12-12 06:56:11
products_009: 
  permalink: classic-product-8
  updated_at: 2008-12-12 06:56:11
  title: Classic Product 8
  id: "205"
  description: 
  category_id: "60"
  created_at: 2008-12-12 06:56:11
products_031: 
  permalink: programs-product-0
  updated_at: 2008-12-12 06:56:11
  title: Programs Product 0
  id: "227"
  description: 
  category_id: "65"
  created_at: 2008-12-12 06:56:11
products_052: 
  permalink: baby-announcements-thank-yous-product-3
  updated_at: 2008-12-12 06:56:11
  title: Baby Announcements & Thank Yous Product 3
  id: "248"
  description: 
  category_id: "72"
  created_at: 2008-12-12 06:56:11
products_011: 
  permalink: classic-product-10
  updated_at: 2008-12-12 06:56:11
  title: Classic Product 10
  id: "207"
  description: 
  category_id: "60"
  created_at: 2008-12-12 06:56:11
products_032: 
  permalink: programs-product-1
  updated_at: 2008-12-12 06:56:11
  title: Programs Product 1
  id: "228"
  description: 
  category_id: "65"
  created_at: 2008-12-12 06:56:11
products_053: 
  permalink: baby-announcements-thank-yous-product-4
  updated_at: 2008-12-12 06:56:11
  title: Baby Announcements & Thank Yous Product 4
  id: "249"
  description: 
  category_id: "72"
  created_at: 2008-12-12 06:56:11
products_033: 
  permalink: programs-product-2
  updated_at: 2008-12-12 06:56:11
  title: Programs Product 2
  id: "229"
  description: 
  category_id: "65"
  created_at: 2008-12-12 06:56:11
products_054: 
  permalink: baby-announcements-thank-yous-product-5
  updated_at: 2008-12-12 06:56:11
  title: Baby Announcements & Thank Yous Product 5
  id: "250"
  description: 
  category_id: "72"
  created_at: 2008-12-12 06:56:11
products_012: 
  permalink: classic-product-11
  updated_at: 2008-12-12 06:56:11
  title: Classic Product 11
  id: "208"
  description: 
  category_id: "60"
  created_at: 2008-12-12 06:56:11
products_055: 
  permalink: baby-announcements-thank-yous-product-6
  updated_at: 2008-12-12 06:56:11
  title: Baby Announcements & Thank Yous Product 6
  id: "251"
  description: 
  category_id: "72"
  created_at: 2008-12-12 06:56:11
products_013: 
  permalink: couture-product-0
  updated_at: 2008-12-12 06:56:11
  title: Couture Product 0
  id: "209"
  description: 
  category_id: "61"
  created_at: 2008-12-12 06:56:11
products_034: 
  permalink: programs-product-3
  updated_at: 2008-12-12 06:56:11
  title: Programs Product 3
  id: "230"
  description: 
  category_id: "65"
  created_at: 2008-12-12 06:56:11
products_014: 
  permalink: couture-product-1
  updated_at: 2008-12-12 06:56:11
  title: Couture Product 1
  id: "210"
  description: 
  category_id: "61"
  created_at: 2008-12-12 06:56:11
products_035: 
  permalink: programs-product-4
  updated_at: 2008-12-12 06:56:11
  title: Programs Product 4
  id: "231"
  description: 
  category_id: "65"
  created_at: 2008-12-12 06:56:11
products_056: 
  permalink: baby-announcements-thank-yous-product-7
  updated_at: 2008-12-12 06:56:11
  title: Baby Announcements & Thank Yous Product 7
  id: "252"
  description: 
  category_id: "72"
  created_at: 2008-12-12 06:56:11
products_015: 
  permalink: couture-product-2
  updated_at: 2008-12-12 06:56:11
  title: Couture Product 2
  id: "211"
  description: 
  category_id: "61"
  created_at: 2008-12-12 06:56:11
products_036: 
  permalink: favour-tags-labels-product-0
  updated_at: 2008-12-12 06:56:11
  title: Favour Tags & Labels Product 0
  id: "232"
  description: 
  category_id: "66"
  created_at: 2008-12-12 06:56:11
products_057: 
  permalink: grad-announcements-thank-yous-product-0
  updated_at: 2008-12-12 06:56:11
  title: Grad Announcements & Thank Yous Product 0
  id: "253"
  description: 
  category_id: "73"
  created_at: 2008-12-12 06:56:11
products_016: 
  permalink: couture-product-3
  updated_at: 2008-12-12 06:56:11
  title: Couture Product 3
  id: "212"
  description: 
  category_id: "61"
  created_at: 2008-12-12 06:56:11
products_037: 
  permalink: favour-tags-labels-product-1
  updated_at: 2008-12-12 06:56:11
  title: Favour Tags & Labels Product 1
  id: "233"
  description: 
  category_id: "66"
  created_at: 2008-12-12 06:56:11
products_058: 
  permalink: grad-announcements-thank-yous-product-1
  updated_at: 2008-12-12 06:56:11
  title: Grad Announcements & Thank Yous Product 1
  id: "254"
  description: 
  category_id: "73"
  created_at: 2008-12-12 06:56:11
products_017: 
  permalink: couture-product-4
  updated_at: 2008-12-12 06:56:11
  title: Couture Product 4
  id: "213"
  description: 
  category_id: "61"
  created_at: 2008-12-12 06:56:11
products_038: 
  permalink: favour-tags-labels-product-2
  updated_at: 2008-12-12 06:56:11
  title: Favour Tags & Labels Product 2
  id: "234"
  description: 
  category_id: "66"
  created_at: 2008-12-12 06:56:11
products_060: 
  permalink: grad-announcements-thank-yous-product-3
  updated_at: 2008-12-12 06:56:11
  title: Grad Announcements & Thank Yous Product 3
  id: "256"
  description: 
  category_id: "73"
  created_at: 2008-12-12 06:56:11
products_059: 
  permalink: grad-announcements-thank-yous-product-2
  updated_at: 2008-12-12 06:56:11
  title: Grad Announcements & Thank Yous Product 2
  id: "255"
  description: 
  category_id: "73"
  created_at: 2008-12-12 06:56:11
products_018: 
  permalink: couture-product-5
  updated_at: 2008-12-12 06:56:11
  title: Couture Product 5
  id: "214"
  description: 
  category_id: "61"
  created_at: 2008-12-12 06:56:11
products_040: 
  permalink: favour-tags-labels-product-4
  updated_at: 2008-12-12 06:56:11
  title: Favour Tags & Labels Product 4
  id: "236"
  description: 
  category_id: "66"
  created_at: 2008-12-12 06:56:11
products_039: 
  permalink: favour-tags-labels-product-3
  updated_at: 2008-12-12 06:56:11
  title: Favour Tags & Labels Product 3
  id: "235"
  description: 
  category_id: "66"
  created_at: 2008-12-12 06:56:11
products_061: 
  permalink: grad-announcements-thank-yous-product-4
  updated_at: 2008-12-12 06:56:11
  title: Grad Announcements & Thank Yous Product 4
  id: "257"
  description: 
  category_id: "73"
  created_at: 2008-12-12 06:56:11
products_020: 
  permalink: destination-product-1
  updated_at: 2008-12-12 06:56:11
  title: Destination Product 1
  id: "216"
  description: 
  category_id: "62"
  created_at: 2008-12-12 06:56:11
products_019: 
  permalink: destination-product-0
  updated_at: 2008-12-12 06:56:11
  title: Destination Product 0
  id: "215"
  description: 
  category_id: "62"
  created_at: 2008-12-12 06:56:11
products_041: 
  permalink: seating-arrangements-product-0
  updated_at: 2008-12-12 06:56:11
  title: Seating Arrangements Product 0
  id: "237"
  description: 
  category_id: "67"
  created_at: 2008-12-12 06:56:11
products_062: 
  permalink: holiday-cards-invitations-product-0
  updated_at: 2008-12-12 06:56:11
  title: Holiday Cards & Invitations Product 0
  id: "258"
  description: 
  category_id: "74"
  created_at: 2008-12-12 06:56:11
products_021: 
  permalink: destination-product-2
  updated_at: 2008-12-12 06:56:11
  title: Destination Product 2
  id: "217"
  description: 
  category_id: "62"
  created_at: 2008-12-12 06:56:11
products_042: 
  permalink: accessories-product-0
  updated_at: 2008-12-12 06:56:11
  title: Accessories Product 0
  id: "238"
  description: 
  category_id: "68"
  created_at: 2008-12-12 06:56:11
products_063: 
  permalink: holiday-cards-invitations-product-1
  updated_at: 2008-12-12 06:56:11
  title: Holiday Cards & Invitations Product 1
  id: "259"
  description: 
  category_id: "74"
  created_at: 2008-12-12 06:56:11
products_022: 
  permalink: destination-product-3
  updated_at: 2008-12-12 06:56:11
  title: Destination Product 3
  id: "218"
  description: 
  category_id: "62"
  created_at: 2008-12-12 06:56:11
products_043: 
  permalink: accessories-product-1
  updated_at: 2008-12-12 06:56:11
  title: Accessories Product 1
  id: "239"
  description: 
  category_id: "68"
  created_at: 2008-12-12 06:56:11
products_064: 
  permalink: holiday-cards-invitations-product-2
  updated_at: 2008-12-12 06:56:11
  title: Holiday Cards & Invitations Product 2
  id: "260"
  description: 
  category_id: "74"
  created_at: 2008-12-12 06:56:11
products_001: 
  permalink: classic-product-0
  updated_at: 2008-12-14 23:26:27
  title: Classic Product 0
  id: "197"
  description: ""
  category_id: "60"
  created_at: 2008-12-12 06:56:11
products_044: 
  permalink: shower-invitations-product-0
  updated_at: 2008-12-12 06:56:11
  title: Shower Invitations Product 0
  id: "240"
  description: 
  category_id: "71"
  created_at: 2008-12-12 06:56:11
products_065: 
  permalink: holiday-cards-invitations-product-3
  updated_at: 2008-12-12 06:56:11
  title: Holiday Cards & Invitations Product 3
  id: "261"
  description: 
  category_id: "74"
  created_at: 2008-12-12 06:56:11
products_002: 
  permalink: classic-product-1
  updated_at: 2008-12-15 06:42:06
  title: Classic Product 1
  id: "198"
  description: ""
  category_id: "60"
  created_at: 2008-12-12 06:56:11
products_023: 
  permalink: destination-product-4
  updated_at: 2008-12-12 06:56:11
  title: Destination Product 4
  id: "219"
  description: 
  category_id: "62"
  created_at: 2008-12-12 06:56:11
products_066: 
  permalink: holiday-cards-invitations-product-4
  updated_at: 2008-12-12 06:56:11
  title: Holiday Cards & Invitations Product 4
  id: "262"
  description: 
  category_id: "74"
  created_at: 2008-12-12 06:56:11
products_003: 
  permalink: classic-product-2
  updated_at: 2008-12-12 06:56:11
  title: Classic Product 2
  id: "199"
  description: 
  category_id: "60"
  created_at: 2008-12-12 06:56:11
products_024: 
  permalink: modern-product-0
  updated_at: 2008-12-12 06:56:11
  title: Modern Product 0
  id: "220"
  description: 
  category_id: "63"
  created_at: 2008-12-12 06:56:11
products_045: 
  permalink: shower-invitations-product-1
  updated_at: 2008-12-12 06:56:11
  title: Shower Invitations Product 1
  id: "241"
  description: 
  category_id: "71"
  created_at: 2008-12-12 06:56:11
products_067: 
  permalink: test
  updated_at: 2008-12-15 07:33:41
  title: Test
  id: "263"
  description: test
  category_id: "60"
  created_at: 2008-12-15 07:33:41
products_004: 
  permalink: classic-product-3
  updated_at: 2008-12-12 06:56:11
  title: Classic Product 3
  id: "200"
  description: 
  category_id: "60"
  created_at: 2008-12-12 06:56:11
products_025: 
  permalink: modern-product-1
  updated_at: 2008-12-12 06:56:11
  title: Modern Product 1
  id: "221"
  description: 
  category_id: "63"
  created_at: 2008-12-12 06:56:11
products_046: 
  permalink: shower-invitations-product-2
  updated_at: 2008-12-12 06:56:11
  title: Shower Invitations Product 2
  id: "242"
  description: 
  category_id: "71"
  created_at: 2008-12-12 06:56:11
products_005: 
  permalink: classic-product-4
  updated_at: 2008-12-12 06:56:11
  title: Classic Product 4
  id: "201"
  description: 
  category_id: "60"
  created_at: 2008-12-12 06:56:11
products_026: 
  permalink: modern-product-2
  updated_at: 2008-12-12 06:56:11
  title: Modern Product 2
  id: "222"
  description: 
  category_id: "63"
  created_at: 2008-12-12 06:56:11
products_047: 
  permalink: shower-invitations-product-3
  updated_at: 2008-12-12 06:56:11
  title: Shower Invitations Product 3
  id: "243"
  description: 
  category_id: "71"
  created_at: 2008-12-12 06:56:11
products_006: 
  permalink: classic-product-5
  updated_at: 2008-12-12 06:56:11
  title: Classic Product 5
  id: "202"
  description: 
  category_id: "60"
  created_at: 2008-12-12 06:56:11
products_027: 
  permalink: modern-product-3
  updated_at: 2008-12-12 06:56:11
  title: Modern Product 3
  id: "223"
  description: 
  category_id: "63"
  created_at: 2008-12-12 06:56:11
products_048: 
  permalink: shower-invitations-product-4
  updated_at: 2008-12-12 06:56:11
  title: Shower Invitations Product 4
  id: "244"
  description: 
  category_id: "71"
  created_at: 2008-12-12 06:56:11
products_007: 
  permalink: classic-product-6
  updated_at: 2008-12-12 06:56:11
  title: Classic Product 6
  id: "203"
  description: 
  category_id: "60"
  created_at: 2008-12-12 06:56:11
products_028: 
  permalink: modern-product-4
  updated_at: 2008-12-12 06:56:11
  title: Modern Product 4
  id: "224"
  description: 
  category_id: "63"
  created_at: 2008-12-12 06:56:11
products_050: 
  permalink: baby-announcements-thank-yous-product-1
  updated_at: 2008-12-12 06:56:11
  title: Baby Announcements & Thank Yous Product 1
  id: "246"
  description: 
  category_id: "72"
  created_at: 2008-12-12 06:56:11
products_049: 
  permalink: baby-announcements-thank-yous-product-0
  updated_at: 2008-12-12 06:56:11
  title: Baby Announcements & Thank Yous Product 0
  id: "245"
  description: 
  category_id: "72"
  created_at: 2008-12-12 06:56:11
